const { db } = require("../firebase");

const axios = require("axios");

const PaymentStatus =
require("./PaymentStatus");

const PaymentResult =
require("./PaymentResult");

class MpesaB2CManager {


/*
=====================================
SEND MONEY
=====================================
*/

async sendMoney(withdrawal) {

    console.log("======================================");
    console.log("MPESA B2C PAYMENT");
    console.log("======================================");

    /*
    =====================================
    VALIDATE WITHDRAWAL
    =====================================
    */

    if (!withdrawal) {
        throw new Error("Withdrawal data is required.");
    }

    console.log("Withdrawal :", withdrawal.id);
    console.log("Reference  :", withdrawal.reference);
    console.log("Agent      :", withdrawal.agentId);
    console.log("Phone      :", withdrawal.phone);
    console.log("Amount     :", withdrawal.amount);

    const amount =
        Number(withdrawal.amount);

    if (
        !Number.isFinite(amount) ||
        amount <= 0
    ) {
        throw new Error(
            `Invalid withdrawal amount: ${withdrawal.amount}`
        );
    }

    /*
    =====================================
    CREATE PAYMENT RECORD
    =====================================
    */

    const paymentRef =
        db.ref("payments").push();

    const paymentId =
        paymentRef.key;

    /*
    =====================================
    LOCAL CORRELATION ID
    =====================================

    This is generated by ParentIQ and sent
    to Safaricom as OriginatorConversationID.

    Keep it short.
    */

    const localOriginatorConversationId =
        `PI${Date.now()}`;

    const now =
        Date.now();

    await paymentRef.set({

        id:
            paymentId,

        withdrawalId:
            withdrawal.id,

        withdrawalReference:
            withdrawal.reference || "",

        agentId:
            withdrawal.agentId,

        phone:
            withdrawal.phone,

        amount,

        provider:
            "MPESA",

        type:
            "B2C",

        status:
            PaymentStatus.PENDING,

        providerReference:
            "",

        conversationId:
            "",

        /*
        ParentIQ-generated identifier.
        */

        localOriginatorConversationId,

        /*
        Safaricom identifier.

        Initially use our local identifier as
        the correlation value. If Safaricom
        returns its own OriginatorConversationID,
        it will be replaced below.
        */

        originatorConversationId:
            localOriginatorConversationId,

        receipt:
            "",

        reconciliationRequired:
            false,

        unknownOutcome:
            false,

        createdAt:
            now,

        updatedAt:
            now

    });

    console.log(
        "Payment created:",
        paymentId
    );

    console.log(
        "Local OriginatorConversationID:",
        localOriginatorConversationId
    );

    /*
    =====================================
    FORMAT PHONE
    =====================================
    */

    let phone =
        String(
            withdrawal.phone || ""
        ).trim();

    /*
    Remove spaces.
    */

    phone =
        phone.replace(/\s+/g, "");

    /*
    Convert:

    +254712345678

    to:

    254712345678
    */

    if (
        phone.startsWith("+")
    ) {
        phone =
            phone.substring(1);
    }

    /*
    Remove all non-digit characters.
    */

    phone =
        phone.replace(/\D/g, "");

    /*
    Convert Kenyan local format:

    0712345678

    to:

    254712345678
    */

    if (
        phone.startsWith("0") &&
        phone.length === 10
    ) {
        phone =
            `254${phone.substring(1)}`;
    }

    /*
    =====================================
    VALIDATE PHONE
    =====================================
    */

    if (
        !/^254\d{9}$/.test(phone)
    ) {

        await paymentRef.update({

            status:
                PaymentStatus.FAILED,

            reconciliationRequired:
                false,

            unknownOutcome:
                false,

            error:
                `Invalid M-Pesa phone number: ${phone}`,

            updatedAt:
                Date.now()

        });

        throw new Error(
            `Invalid M-Pesa phone number: ${phone}`
        );
    }

    console.log(
        "Formatted Phone:",
        phone
    );

    /*
    =====================================
    VALIDATE ENVIRONMENT
    =====================================
    */

    if (!process.env.BASE_URL) {
        throw new Error(
            "BASE_URL is missing."
        );
    }

    if (!process.env.CONSUMER_KEY) {
        throw new Error(
            "CONSUMER_KEY is missing."
        );
    }

    if (!process.env.CONSUMER_SECRET) {
        throw new Error(
            "CONSUMER_SECRET is missing."
        );
    }

    if (!process.env.INITIATOR_NAME) {
        throw new Error(
            "INITIATOR_NAME is missing."
        );
    }

    if (!process.env.SECURITY_CREDENTIAL) {
        throw new Error(
            "SECURITY_CREDENTIAL is missing."
        );
    }

    if (!process.env.SHORTCODE) {
        throw new Error(
            "SHORTCODE is missing."
        );
    }

    if (!process.env.CALLBACK_BASE_URL) {
        throw new Error(
            "CALLBACK_BASE_URL is missing."
        );
    }

    /*
    =====================================
    ACCESS TOKEN
    =====================================
    */

    const token =
        await this.getAccessToken();

    if (!token) {
        throw new Error(
            "M-Pesa access token was not generated."
        );
    }

    /*
    =====================================
    BUILD B2C PAYLOAD
    =====================================
    */

    const payload = {

        OriginatorConversationID:
            localOriginatorConversationId,

        InitiatorName:
            process.env.INITIATOR_NAME,

        SecurityCredential:
            process.env.SECURITY_CREDENTIAL,

        CommandID:
            "BusinessPayment",

        Amount:
            amount,

        PartyA:
            process.env.SHORTCODE,

        PartyB:
            phone,

        Remarks:
            "ParentIQ Withdrawal",

        QueueTimeOutURL:
            `${process.env.CALLBACK_BASE_URL}/mpesa/b2c/timeout`,

        ResultURL:
            `${process.env.CALLBACK_BASE_URL}/mpesa/b2c/result`,

        Occasion:
            "Withdrawal"

    };

    /*
    =====================================
    SEND B2C REQUEST
    =====================================
    */

    try {

        console.log(
            "========== B2C REQUEST =========="
        );

        /*
        NEVER LOG SecurityCredential.
        */

        console.log({

            OriginatorConversationID:
                payload.OriginatorConversationID,

            InitiatorName:
                payload.InitiatorName,

            CommandID:
                payload.CommandID,

            Amount:
                payload.Amount,

            PartyA:
                payload.PartyA,

            PartyB:
                payload.PartyB,

            Remarks:
                payload.Remarks,

            QueueTimeOutURL:
                payload.QueueTimeOutURL,

            ResultURL:
                payload.ResultURL,

            Occasion:
                payload.Occasion,

            SecurityCredential:
                "[REDACTED]"

        });

        /*
        =====================================
        CALL SAFARICOM B2C API
        =====================================
        */

        const response =
            await axios.post(

                `${process.env.BASE_URL}/mpesa/b2c/v1/paymentrequest`,

                payload,

                {

                    timeout:
                        30000,

                    headers: {

                        Authorization:
                            `Bearer ${token}`,

                        "Content-Type":
                            "application/json",

                        Accept:
                            "application/json"

                    }

                }

            );

        console.log(
            "========== B2C RESPONSE =========="
        );

        console.log(
            response.data
        );

        /*
        =====================================
        EXTRACT SAFARICOM RESPONSE
        =====================================
        */

        const conversationId =
            response.data?.ConversationID ||
            "";

        /*
        Safaricom should normally return this.

        If it doesn't, retain our original
        correlation identifier so the callback
        can still find the payment record.
        */

        const originatorConversationId =
            response.data?.OriginatorConversationID ||
            localOriginatorConversationId;

        const responseCode =
            response.data?.ResponseCode;

        const responseDescription =
            response.data?.ResponseDescription ||
            "";

        /*
        =====================================
        VERIFY INITIAL RESPONSE
        =====================================
        */

        /*
        The B2C submission acknowledgement is
        not the final payment result.

        A successful HTTP response means the
        request was accepted for processing.

        Final payment status comes through
        ResultURL.
        */

        /*
        =====================================
        UPDATE PAYMENT RECORD
        =====================================
        */

        await paymentRef.update({

            providerReference:
                conversationId,

            conversationId:
                conversationId,

            localOriginatorConversationId:
                localOriginatorConversationId,

            originatorConversationId:
                originatorConversationId,

            responseCode:
                responseCode,

            responseDescription:
                responseDescription,

            rawResponse:
                response.data,

            status:
                PaymentStatus.PENDING,

            reconciliationRequired:
                false,

            unknownOutcome:
                false,

            updatedAt:
                Date.now()

        });

        console.log(
            "B2C request accepted."
        );

        console.log(
            "Payment ID:",
            paymentId
        );

        console.log(
            "ConversationID:",
            conversationId
        );

        console.log(
            "OriginatorConversationID:",
            originatorConversationId
        );

        /*
        =====================================
        RETURN PROCESSING RESULT
        =====================================
        */

        return new PaymentResult({

            success:
                true,

            paymentId,

            provider:
                "MPESA",

            status:
                PaymentStatus.PENDING,

            providerReference:
                conversationId,

            conversationId:
                conversationId,

            originatorConversationId:
                originatorConversationId,

            receipt:
                "",

            reconciliationRequired:
                false,

            unknownOutcome:
                false,

            message:
                responseDescription

        });

    }

    catch (error) {

        console.log(
            "========== B2C ERROR =========="
        );

        const httpStatus =
            error.response?.status;

        const errorCode =
            String(
                error.code || ""
            ).toUpperCase();

        let message =
            error.message ||
            "Unknown M-Pesa B2C error.";

        /*
        =====================================
        CAPTURE PROVIDER RESPONSE
        =====================================
        */

        if (error.response) {

            console.log(
                "HTTP:",
                httpStatus
            );

            console.log(
                "Response:",
                error.response.data
            );

            message =
                typeof error.response.data === "string"
                    ? error.response.data
                    : JSON.stringify(
                        error.response.data
                    );

        }
        else {

            console.log(
                "Error:",
                error.message
            );

        }

        /*
        =====================================
        DETERMINE UNKNOWN OUTCOME
        =====================================

        These conditions do NOT prove that
        Safaricom rejected the payout.

        The request may have reached Safaricom
        even though ParentIQ did not receive a
        definitive response.

        Therefore:

        UNKNOWN
            -> keep payment unresolved
            -> reconciliation required
            -> do NOT restore wallet
        */

        const unknownOutcome =
            !error.response ||
            errorCode === "ETIMEDOUT" ||
            errorCode === "ECONNRESET" ||
            errorCode === "ECONNABORTED" ||
            errorCode === "ERR_NETWORK" ||
            errorCode === "NETWORK_ERROR" ||
            httpStatus === 409 ||
            httpStatus === 429 ||
            (
                typeof httpStatus === "number" &&
                httpStatus >= 500
            ) ||
            String(
                error.message || ""
            ).toLowerCase().includes("timeout") ||
            String(
                error.message || ""
            ).toLowerCase().includes("timed out") ||
            String(
                error.message || ""
            ).toLowerCase().includes("socket hang up") ||
            String(
                error.message || ""
            ).toLowerCase().includes("connection reset");

        /*
        =====================================
        UNKNOWN / UNCERTAIN RESULT
        =====================================
        */

        if (unknownOutcome) {

            console.log(
                "B2C outcome is UNKNOWN."
            );

            console.log(
                "Payment requires reconciliation."
            );

            /*
            IMPORTANT:

            Do NOT mark the payment FAILED.

            Do NOT restore the wallet here.

            The withdrawal route will detect
            reconciliationRequired / unknownOutcome
            and keep the withdrawal reserved.
            */

            await paymentRef.update({

                status:
                    PaymentStatus.PENDING,

                reconciliationRequired:
                    true,

                unknownOutcome:
                    true,

                error:
                    message,

                updatedAt:
                    Date.now()

            });

            /*
            Throw an Error with explicit flags.

            withdrawals.js already has:

            isUnknownProviderError(error)

            and will therefore move the withdrawal
            to RECONCILIATION_REQUIRED.
            */

            const reconciliationError =
                new Error(
                    "M-Pesa payout outcome is uncertain. Reconciliation is required."
                );

            reconciliationError.reconciliationRequired =
                true;

            reconciliationError.unknownOutcome =
                true;

            reconciliationError.uncertain =
                true;

            reconciliationError.originalMessage =
                message;

            reconciliationError.code =
                errorCode || "UNKNOWN_PROVIDER_OUTCOME";

            reconciliationError.response =
                error.response;

            throw reconciliationError;

        }

        /*
        =====================================
        CONFIRMED PROVIDER REJECTION
        =====================================

        We received an actual provider response
        and it is not classified as uncertain.

        This is a confirmed submission failure.

        The route can safely call
        WithdrawalManager.markPaymentFailed()
        and restore the reserved wallet.
        */

        console.log(
            "B2C request was rejected."
        );

        console.log(
            "HTTP status:",
            httpStatus
        );

        await paymentRef.update({

            status:
                PaymentStatus.FAILED,

            reconciliationRequired:
                false,

            unknownOutcome:
                false,

            error:
                message,

            updatedAt:
                Date.now()

        });

        /*
        =====================================
        RETURN CONFIRMED FAILURE
        =====================================
        */

        return new PaymentResult({

            success:
                false,

            paymentId,

            provider:
                "MPESA",

            status:
                PaymentStatus.FAILED,

            reconciliationRequired:
                false,

            unknownOutcome:
                false,

            message:
                message

        });

    }

}

/*
=====================================
GET ACCESS TOKEN
=====================================
*/

async getAccessToken() {

    const consumerKey =
        process.env.CONSUMER_KEY;

    const consumerSecret =
        process.env.CONSUMER_SECRET;

    if (
        !consumerKey ||
        !consumerSecret
    ) {

        throw new Error(
            "M-Pesa consumer credentials are missing."
        );

    }

    const auth =
        Buffer.from(
            `${consumerKey}:${consumerSecret}`
        ).toString("base64");

    console.log(
        "Getting B2C Access Token..."
    );

    try {

        const response =
            await axios.get(

                `${process.env.BASE_URL}/oauth/v1/generate?grant_type=client_credentials`,

                {

                    timeout:
                        30000,

                    headers: {

                        Authorization:
                            `Basic ${auth}`,

                        Accept:
                            "application/json"

                    }

                }

            );

        const token =
            response.data?.access_token;

        if (!token) {

            throw new Error(
                "M-Pesa OAuth response did not contain an access token."
            );

        }

        console.log(
            "B2C Access Token Generated"
        );

        return token;

    }

    catch (error) {

        console.log(
            "========== M-PESA OAUTH ERROR =========="
        );

        if (error.response) {

            console.log(
                "HTTP:",
                error.response.status
            );

            console.log(
                "Response:",
                error.response.data
            );

        }
        else {

            console.log(
                "Error:",
                error.message
            );

        }

        throw error;

    }

}

}


module.exports =
new MpesaB2CManager();
