module.exports = {

    SUBSCRIPTION_PAYMENT: "SUBSCRIPTION_PAYMENT",

    COMMISSION_EARNED: "COMMISSION_EARNED",

    WITHDRAWAL_REQUESTED: "WITHDRAWAL_REQUESTED",

    WITHDRAWAL_APPROVED: "WITHDRAWAL_APPROVED",

    WITHDRAWAL_PAID: "WITHDRAWAL_PAID",

    WITHDRAWAL_REJECTED: "WITHDRAWAL_REJECTED",

    REFUND: "REFUND",

    ADJUSTMENT: "ADJUSTMENT"

};